// import type { Card } from '@/types/flashcards';

// export const mockCards: Card[] = [
//   { id: '1', word: 'serendipity', sourceLanguage: 'English', targetLanguage: 'Ukrainian', translation: 'щасливий випадок', explanation: 'A fortunate discovery made by chance.', createdByAi: true, easeFactor: 2.6, repetitions: 4, interval: 14, nextReviewDate: new Date(Date.now() + 86400000).toISOString(), lastReviewedAt: new Date(Date.now() - 86400000 * 13).toISOString(), isLeech: false, categoryId: 'daily' },
//   { id: '2', word: 'wanderlust', sourceLanguage: 'English', targetLanguage: 'Ukrainian', translation: 'жага до подорожей', explanation: 'A strong desire to travel and explore the world.', createdByAi: true, easeFactor: 2.4, repetitions: 3, interval: 7, nextReviewDate: new Date().toISOString(), lastReviewedAt: new Date(Date.now() - 86400000 * 7).toISOString(), isLeech: false, categoryId: 'travel' },
//   { id: '3', word: 'thorough', sourceLanguage: 'English', targetLanguage: 'Ukrainian', translation: 'ретельний, ґрунтовний', explanation: 'Complete with regard to every detail.', createdByAi: false, easeFactor: 2.5, repetitions: 2, interval: 3, nextReviewDate: new Date(Date.now() + 86400000 * 2).toISOString(), lastReviewedAt: new Date(Date.now() - 86400000 * 3).toISOString(), isLeech: false, categoryId: 'work' },
//   { id: '4', word: 'deadline', sourceLanguage: 'English', targetLanguage: 'Ukrainian', translation: 'кінцевий термін', explanation: 'The latest time or date by which something should be completed.', createdByAi: true, easeFactor: 2.5, repetitions: 1, interval: 1, nextReviewDate: new Date(Date.now() - 86400000).toISOString(), lastReviewedAt: new Date(Date.now() - 86400000).toISOString(), isLeech: false, categoryId: 'work' },
//   { id: '5', word: 'subtle', sourceLanguage: 'English', targetLanguage: 'Ukrainian', translation: 'ледь помітний, тонкий', explanation: 'So delicate or precise as to be difficult to analyze or describe.', createdByAi: false, easeFactor: 2.1, repetitions: 1, interval: 1, nextReviewDate: new Date(Date.now() - 86400000 * 2).toISOString(), lastReviewedAt: new Date(Date.now() - 86400000 * 2).toISOString(), isLeech: true, categoryId: 'daily' },
// ];
